[web]
web-01 ansible_host=192.168.1.101 ansible_user=ubuntu

[db]
db-01 ansible_host=192.168.1.102 ansible_user=ubuntu

[monitor]
monitor-01 ansible_host=192.168.1.103 ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
