---
- name: Configure web-01 (Flask + Docker)
  hosts: web
  become: true
  roles:
    - web

- name: Configure db-01 (PostgreSQL)
  hosts: db
  become: true
  roles:
    - db

- name: Configure monitor-01 (Monitoring tools)
  hosts: monitor
  become: true
  roles:
    - monitor
